version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: air main.go #-b 0.0.0.0 #air main.go -b 0.0.0.0
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: